# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant setup to use virtualbox and have a base config of the VMs
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.ssh.insert_key = false
  config.vm.boot_timeout = 600
  config.vm.box_check_update = false

  # Define the edge-router VM
  config.vm.define "edge-router" do |router|
    router.vm.box = "debian/bullseye64"
    router.vm.hostname = "edge-router"
    router.vm.network "public_network", ip: "150.150.150.3" # WAN (here the interconnection with Thomas and Pierre)
    router.vm.network "private_network", ip: "192.169.1.1", virtualbox__intnet: "DMZ"
    router.vm.network "private_network", ip: "42.42.42.1", virtualbox__intnet: "LAN"

    router.vm.provision "shell", inline: <<-SHELL # Shell commands up until the "SHELL" keyword
      apt-get update
      apt-get install -y iptables nginx curl isc-dhcp-server 

      # Enable IP forwarding
      echo 1 > /proc/sys/net/ipv4/ip_forward
      echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
      sysctl -p

      # Configure DHCP server
      cat > /etc/dhcp/dhcpd.conf <<EOL
        subnet 42.42.42.0 netmask 255.255.255.0 {
          range 42.42.42.100 42.42.42.254;
          option routers 42.42.42.1;
          option domain-name-servers 192.169.1.20;
          option subnet-mask 255.255.255.0;
          default-lease-time 600;
          max-lease-time 7200;
        }
EOL
      # troubleshoot client-side : cat /var/lib/dhcp/dhclient.leases

      # Set the interface for DHCP server
      sed -i 's/INTERFACESv4=""/INTERFACESv4="eth3"/' /etc/default/isc-dhcp-server

      # Start DHCP server
      systemctl restart isc-dhcp-server

      ### IPTABLES RULES
      ## Flush existing rules
      iptables -F
      iptables -X
      iptables -t nat -F
      iptables -t nat -X

      # Set default policies
      iptables -P INPUT ACCEPT
      iptables -P OUTPUT ACCEPT
      iptables -P FORWARD DROP

      # Enable NAT between LAN and WANEdit Readme
      iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

      # Allow traffic from the LAN to the DMZ
      iptables -A FORWARD -p icmp -j ACCEPT
      iptables -A FORWARD -i eth3 -o eth2 -p tcp -j ACCEPT
      iptables -A FORWARD -i eth2 -o eth3 -p tcp -j ACCEPT
      iptables -A FORWARD -i eth3 -o eth2 -p udp -j ACCEPT
      iptables -A FORWARD -i eth2 -o eth3 -p udp -j ACCEPT

      # Allow traffic between Internet and the DMZ (DNS)
      iptables -A FORWARD -i eth2 -o eth1 -p udp --dport 53 -j ACCEPT
      iptables -A FORWARD -i eth1 -o eth2 -p udp --sport 53 -j ACCEPT

      # Allow traffic between Client and the DMZ (DNS + HTTP)
      iptables -A FORWARD -i eth3 -o eth2 -p udp --dport 53 -j ACCEPT
      iptables -A FORWARD -i eth2 -o eth3 -p udp --sport 53 -j ACCEPT
      iptables -A FORWARD -i eth3 -o eth2 -p udp --dport 80 -j ACCEPT
      iptables -A FORWARD -i eth2 -o eth3 -p udp --sport 80 -j ACCEPT

      # Allow clients to access the internet
      iptables -A FORWARD -i eth3 -o eth1 -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      iptables -A FORWARD -i eth1 -o eth3 -p tcp --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT

      # Display the rules to verify
      iptables -L -v
      iptables -t nat -L -v

      # Setup nginx
      mkdir -p /etc/nginx/conf.d
      cat > /etc/nginx/nginx.conf <<EOL
      user www-data;
      worker_processes auto;
      error_log /var/log/nginx/error.log;
      pid /run/nginx.pid;

      events {
          worker_connections 1024;
      }

      http {
          include             /etc/nginx/mime.types;
          default_type        application/octet-stream;

          include /etc/nginx/conf.d/*.conf;
      }
EOL
      #Default webpage indicating error 404 for any request that is associated to the below subdomains.
      cat > /etc/nginx/conf.d/default.conf <<'EOL'
      server {
          listen 80 default_server;
          server_name _;

          location / {
              return 404;
          }
      }
EOL
      #'EOL' is bash specificity to make sure the $variables are not interpreted up until the "End Of File" string
      cat > /etc/nginx/conf.d/web1.conf <<'EOL'
      server {
          listen 80;
          server_name web1.yfrancois.webserver.com;

          location / {
              proxy_pass http://192.169.1.20:8081;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }
EOL

      cat > /etc/nginx/conf.d/web2.conf <<'EOL'
      server {
          listen 80;
          server_name web2.yfrancois.webserver.com;

          location / {
              proxy_pass http://192.169.1.20:8082;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }
EOL

      cat > /etc/nginx/conf.d/edgeshark.conf <<'EOL'
      server {
          listen 80;
          server_name edgeshark.yfrancois.webserver.com;

          location / {
              proxy_pass http://192.169.1.20:5001;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }
EOL
      # Restart nginx to apply the new configuration
      systemctl restart nginx
      echo "nameserver 192.169.1.20" > /etc/resolv.conf
      ip route del default
SHELL
  end

  # Define the services VM with Edgeshark and other services.
  config.vm.define "services" do |services|
    services.vm.box = "debian/bullseye64"
    services.vm.hostname = "services"
    services.vm.network "private_network", ip: "192.169.1.20", virtualbox__intnet: "DMZ"

    # Set up port forwarding for services in this VM.
    services.vm.network "forwarded_port", guest: 80, host: 8080 # For webserver (Apache) 
    services.vm.network "forwarded_port", guest: 8081, host: 8081 # For web1 (Nginx)
    services.vm.network "forwarded_port", guest: 8082, host: 8082 # For web2 (Nginx)
    services.vm.network "forwarded_port", guest: 5001, host: 5001 # For Edgeshark

    services.vm.provision "shell", inline: <<-SHELL
      # Update and install necessary packages.
      apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release docker.io bind9 bind9utils bind9-doc

      # Add vagrant user to the docker group.
      usermod -aG docker vagrant
      
      # Create necessary directories for services.
      mkdir -p /home/vagrant/services/web1 /home/vagrant/services/web2 /home/vagrant/services/webserver

      # Create necessary directories for BIND configuration.
      mkdir -p /etc/bind/zones
      
      # Add routes for WAN and LAN networks and default gateway.
      ip route add 150.150.150.0/24 via 192.169.1.1
      ip route add 42.42.42.0/24 via 192.169.1.1
      ip route add add 192.169.1.0/24 via 192.169.1.1

      # Install Edgeshark using t    #router.vm.network "forwarded_port", guest: 80, host: 8088 
      wget -q --no-cache -O /tmp/edgeshark.sh https://github.com/siemens/edgeshark/raw/main/deployments/nocomposer/edgeshark.sh
      chmod +x /tmp/edgeshark.sh
      
      # Run Edgeshark installation script.
      if ! DOCKER_DEFAULT_PLATFORM= bash /tmp/edgeshark.sh up; then
          echo "Edgeshark installation failed."
          exit 1
      fi

      # Start the web1 container (Nginx).
      if ! docker run -d --name web1 -p 8081:80 -v /home/vagrant/services/web1:/usr/share/nginx/html:ro nginx:alpine; then
          echo "Failed to start web1 container."
          exit 1
      fi

      # Start the web2 container (Nginx).
      if ! docker run -d --name web2 -p 8082:80 -v /home/vagrant/services/web2:/usr/share/nginx/html:ro nginx:alpine; then
          echo "Failed to start web2 container."
          exit 1
      fi

      # Create index.html files for each web nginx service.
      echo "<h1>Welcome to Web1</h1>" > /home/vagrant/services/web1/index.html 
      echo "<h1>Welcome to Web2</h1>" > /home/vagrant/services/web2/index.html 

      #DNS config
      cat > /etc/bind/named.conf.local <<'EOL'
        zone "yfrancois.webserver.com" {
          type master;
          file "/etc/bind/db.yfrancois.webserver.com";
        };
EOL
      # Create db.example.com zone file
      cat > /etc/bind/db.yfrancois.webserver.com <<'EOL'
$TTL    604800
@       IN      SOA     yfrancois.webserver.com. admin.yfrancois.webserver.com. (
                        2023113001 ; Serial
                        604800     ; Refresh
                        86400      ; Retry
                        2419200    ; Expire
                        604800 )   ; Negative Cache TTL

; Nom de serveur DNS
@       IN      NS      ns.yfrancois.webserver.com.

; Adresse IP du serveur DNS
ns      IN      A       192.169.1.20

; Enregistrement pour yfrancois.webserver.com
@       IN      A       192.169.1.20

web1    IN     A        155.155.155.3

web2    IN     A        155.155.155.3

edgeshark IN   A        155.155.155.3
EOL

# Create db.example.com zone file
cat > /etc/bind/named.conf.options <<EOL
\options {
    directory "/var/cache/bind";

    listen-on { 192.169.1.20; };

    allow-query { any; };
    recursion yes;

    forwarders {
        150.150.150.254;  
    };
    forward only;
    max-recursion-queries 10;
    max-recursion-depth 5;
    
    dnssec-validation no;
};
EOL
      # Restart BIND9 to apply changes
      #chown bind:bind /etc/bind/db.yfrancois.webserver.com
      #chmod 644 /etc/bind/zones/db.yfrancois.webserver.com
      # Change ownership to bind user and group
      #sudo chown bind:bind /etc/bind/zones/db.yfrancois.webserver.com
      sudo chown bind:bind /etc/bind/named.conf.local

      # Set appropriate permissions
      #sudo chmod 644 /etc/bind/zones/db.yfrancois.webserver.com
      sudo chmod 644 /etc/bind/named.conf.local
      systemctl restart bind9
      
      ip route del default
      ip route add default via 192.169.1.1 #default route to the edge router
SHELL
end

  ## The external client is for debug purpose.
  ## Helpful when it comes to visualising what happens on my side of the architecture.
  # # Define external client
  # config.vm.define "external-client" do |client|
  #   client.vm.box = "bento/ubuntu-22.04"
  #   client.vm.hostname = "external-client"
  #   client.vm.network "private_network", ip: "150.150.150.10", virtualbox__intnet: "WAN"

  #   client.vm.provision "shell", inline: <<-SHELL
  #     apt-get update
  #     apt-get install -y w3m curl dnsutils
  #     echo "nameserver 192.169.1.20" > /etc/resolv.conf
  #     ip route del default
  #     ip route add default via 10.0.0.1
  #     # Add routes for services
  #     ip route add 192.168.1.0/24 via 10.0.0.1

  #   SHELL
  # end

  # # Define external client
  # config.vm.define "external-client" do |client|
  #   client.vm.box = "bento/ubuntu-22.04"
  #   client.vm.hostname = "external-client"
  #   client.vm.network "private_network", ip: "10.0.0.100", virtualbox__intnet: "WAN"

  #   client.vm.provision "shell", inline: <<-SHELL
  #     apt-get update
  #     apt-get install -y w3m curl dnsutils
  #     echo "nameserver 192.169.1.20" > /etc/resolv.conf
  #     ip route del default
  #     ip route add default via 10.0.0.1
  #     # Add routes for services
  #     ip route add 192.168.1.0/24 via 10.0.0.1
  #   SHELL
  # end

  # Define LAN client
  config.vm.define "lan-client" do |client|
    client.vm.box = "debian/bullseye64"
    client.vm.hostname = "lan-client"
    client.vm.network "private_network", ip: "42.42.42.100", virtualbox__intnet: "LAN"
    #client.vm.network "private_network", type: "dhcp", virtualbox__intnet: "LAN"
    client.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl w3m dnsutils
      
        #wireshark
      tasksel install xfce-desktop
      echo "nameserver 192.169.1.20" > /etc/resolv.conf # static DNS server 
      ip route del default
      ip route add default via 42.42.42.1 # static default GW
      # Add routes for services
      ip route add 192.168.1.0/24 via 42.42.42.1
    SHELL
  end
end

##After boot
# ifdown eth0 # Deactivate NAT port used for provisionning the VM
# ifdown eth1
# ifup eth1 # Activate the interface to get an IP address from the DHCP server
